language: groovy
sudo: false
jdk:
- oraclejdk7

branches:
  only:
  - master

branches:
  only:
  - master

script:
  - ./gradlew clean test assemble

notifications:
  email:
    recipients:
      - benjamin.muschko@gmail.com
      - aruizca@gmail.com
