language: groovy

jdk:
- oraclejdk7

branches:
  only:
  - master

before_install:
- rm -rf ~/.gvm
- curl -s get.gvmtool.net > ~/install_gvm.sh
- chmod 775 ~/install_gvm.sh
- ~/install_gvm.sh
- echo "gvm_auto_answer=true" > ~/.gvm/etc/config
- source ~/.gvm/bin/gvm-init.sh
- GRAILS_VERSION=`grep '^grailsVersion=' ./gradle.properties | sed -e
  's/^grailsVersion=//g'`
- gvm install grails $GRAILS_VERSION || true

branches:
  only:
  - master

script:
  - ./gradlew clean test assemble

notifications:
  email:
    recipients:
      - benjamin.muschko@gmail.com
      - aruizca@gmail.com
      - mansi.arora@tothenew.com
      - uday.singh@tothenew.com
